### ISSUE TITLE
[Bug]: requiredDropCapabilities transation to Kyverno Policies seems incorrect

### ISSUE THREAD

**Issue by okhotnikov-aa** [appvia/psp-migration#277]
### What happened?

PSP with such an option  as below, afaik don't require to strict drop of capabilities in Pod manifest. It just prevents to create pod with such capabilityes.

```
requiredDropCapabilities:
  - CHOWN
```

Policy created with psp-migrator for Kyverno - require to strict drop capability in Pod manifest

```
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: tenant-nonroot-psp-requireddropcapabilities
spec:
  rules:
    - validate:
        pattern:
          spec:
            containers:
              - securityContext:
                  capabilities:
                    drop:
                      - CHOWN
```

So there is significant difference in logic between original PSP and migrated Kyverno Policy
(Or maybe i just misunderstood something?)
