### ISSUE TITLE
[Bug]: Volumes aren't converted properly

### ISSUE THREAD

**Issue by Clijsters** [appvia/psp-migration#295]
### What happened?

While converting a PSP with any spec.volumes in it, the kyverno policy doesn't use the provided volumes list, but a hard coded one from [kyverno.ts#111](https://github.com/appvia/psp-migration/blob/main/src/kyverno.ts#L111), so the output is:

```
conditions:
            all:
              - key: "{{ request.object.spec.volumes[].keys(@)[] }}"
                operator: AnyNotIn
                value:
                  - name
                  - projected
                  - emptyDir
```

My wild guess is that the hard coded list should be replaced with smth like exactly done in the capabilities section at [kyverno.ts#190](https://github.com/appvia/psp-migration/blob/main/src/kyverno.ts#L190)

### What policy engine were you generating policy for

Kynvero
