### ISSUE TITLE
[FeatureRequest]: use any in match filter due to deprecation

### ISSUE THREAD

**Issue by jkleinlercher** [appvia/psp-migration#297]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What is the idea?

According to https://kyverno.io/docs/writing-policies/match-exclude/#resource-filters :

> Specifying resource filters directly under match and exclude has been marked for deprecation and will be removed in a future release. It is highly recommended you specify them under any or all blocks.

However the psp-migration tool returns filters like this:

```
      match:
        resources:
          kinds:
            - Pod
```

should be

```
      match:
        any:
        - resources:
            kinds:
              - Pod
```
